-- DDL da camada bronze — GERADO por gerar_ddl_bronze.py. Não editar à mão.
-- Origem: descoberta de 19 objeto(s) do CVDW.

CREATE SCHEMA IF NOT EXISTS bronze;

-- Controle de carga incremental (última data de referência por objeto).
CREATE TABLE IF NOT EXISTS bronze._ingestao_controle (
    nome_logico            text PRIMARY KEY,
    ultima_data_referencia timestamptz,
    ultima_execucao        timestamptz,
    ultimo_modo            text,
    registros_ultima_carga bigint,
    status                 text,
    mensagem               text
);

-- ===== reservas (reservas) =====
CREATE TABLE IF NOT EXISTS bronze.reservas (
    _id_tecnico bigint GENERATED ALWAYS AS IDENTITY,
    referencia numeric,
    referencia_data timestamptz,
    ativo text,
    idreserva numeric,
    data_cad timestamptz,
    codigointerno text,
    numero_venda text,
    aprovada text,
    data_venda timestamptz,
    situacao text,
    idsituacao numeric,
    situacao_comercial text,
    idempreendimento numeric,
    codigointerno_empreendimento numeric,
    empreendimento text,
    data_entrega_chaves_contrato_cliente text,
    etapa text,
    bloco text,
    unidade text,
    regiao text,
    venda text,
    idcliente numeric,
    documento_cliente text,
    cliente text,
    email text,
    cidade text,
    cep_cliente text,
    renda numeric,
    sexo text,
    idade numeric,
    estado_civil text,
    idcorretor numeric,
    corretor text,
    idimobiliaria numeric,
    imobiliaria text,
    valor_contrato numeric,
    valor_contrato_com_juros numeric,
    vencimento text,
    campanha text,
    cessao text,
    motivo_cancelamento text,
    data_cancelamento text,
    espacos_complementares text,
    idlead text,
    data_ultima_alteracao_situacao text,
    idempresa_correspondente text,
    empresa_correspondente text,
    valor_fgts numeric,
    valor_financiamento numeric,
    valor_subsidio numeric,
    nome_usuario text,
    idunidade numeric,
    idprecadastro numeric,
    idmidia numeric,
    midia text,
    descricao_motivo_cancelamento text,
    idsituacao_anterior numeric,
    situacao_anterior text,
    idtabela numeric,
    nometabela text,
    codigointernotabela text,
    idtipo_tabela text,
    tipo_tabela text,
    data_contrato text,
    valor_proposta numeric,
    vpl_reserva numeric,
    valor_liquido_com_juros numeric,
    valor_liquido_sem_juros numeric,
    vgv_tabela numeric,
    vpl_tabela numeric,
    usuario_aprovacao text,
    data_aprovacao timestamptz,
    juros_condicao_aprovada numeric,
    juros_apos_entrega_condicao_aprovada numeric,
    idtabela_condicao_aprovada numeric,
    data_primeira_aprovacao text,
    aprovacao_absoluto numeric,
    aprovacao_vpl_valor numeric,
    idtipovenda text,
    tipovenda text,
    idgrupo text,
    grupo text,
    data_modificacao timestamptz,
    idgestor_time text,
    nome_time text,
    juros_apos_entrega_cadastro text,
    juros_cadastro_fixa_adicional text,
    juros_cadastro text,
    data_entrega text,
    vgv_tabela_minima text,
    vpl_tabela_minima text,
    idtime text,
    campos_adicionais jsonb,
    campos_adicionais_contrato jsonb,
    _hash_linha text NOT NULL,
    _data_extracao timestamptz NOT NULL DEFAULT now(),
    _pagina integer,
    CONSTRAINT pk_reservas PRIMARY KEY (_id_tecnico)
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_reservas_chave ON bronze.reservas (idreserva);
-- (índice por id de negócio garantido por ux_reservas_chave em idreserva)
CREATE TABLE IF NOT EXISTS bronze.reservas_snapshot (
    _id_snapshot bigint GENERATED ALWAYS AS IDENTITY,
    _data_snapshot date NOT NULL DEFAULT CURRENT_DATE,
    referencia numeric,
    referencia_data timestamptz,
    ativo text,
    idreserva numeric,
    data_cad timestamptz,
    codigointerno text,
    numero_venda text,
    aprovada text,
    data_venda timestamptz,
    situacao text,
    idsituacao numeric,
    situacao_comercial text,
    idempreendimento numeric,
    codigointerno_empreendimento numeric,
    empreendimento text,
    data_entrega_chaves_contrato_cliente text,
    etapa text,
    bloco text,
    unidade text,
    regiao text,
    venda text,
    idcliente numeric,
    documento_cliente text,
    cliente text,
    email text,
    cidade text,
    cep_cliente text,
    renda numeric,
    sexo text,
    idade numeric,
    estado_civil text,
    idcorretor numeric,
    corretor text,
    idimobiliaria numeric,
    imobiliaria text,
    valor_contrato numeric,
    valor_contrato_com_juros numeric,
    vencimento text,
    campanha text,
    cessao text,
    motivo_cancelamento text,
    data_cancelamento text,
    espacos_complementares text,
    idlead text,
    data_ultima_alteracao_situacao text,
    idempresa_correspondente text,
    empresa_correspondente text,
    valor_fgts numeric,
    valor_financiamento numeric,
    valor_subsidio numeric,
    nome_usuario text,
    idunidade numeric,
    idprecadastro numeric,
    idmidia numeric,
    midia text,
    descricao_motivo_cancelamento text,
    idsituacao_anterior numeric,
    situacao_anterior text,
    idtabela numeric,
    nometabela text,
    codigointernotabela text,
    idtipo_tabela text,
    tipo_tabela text,
    data_contrato text,
    valor_proposta numeric,
    vpl_reserva numeric,
    valor_liquido_com_juros numeric,
    valor_liquido_sem_juros numeric,
    vgv_tabela numeric,
    vpl_tabela numeric,
    usuario_aprovacao text,
    data_aprovacao timestamptz,
    juros_condicao_aprovada numeric,
    juros_apos_entrega_condicao_aprovada numeric,
    idtabela_condicao_aprovada numeric,
    data_primeira_aprovacao text,
    aprovacao_absoluto numeric,
    aprovacao_vpl_valor numeric,
    idtipovenda text,
    tipovenda text,
    idgrupo text,
    grupo text,
    data_modificacao timestamptz,
    idgestor_time text,
    nome_time text,
    juros_apos_entrega_cadastro text,
    juros_cadastro_fixa_adicional text,
    juros_cadastro text,
    data_entrega text,
    vgv_tabela_minima text,
    vpl_tabela_minima text,
    idtime text,
    campos_adicionais jsonb,
    campos_adicionais_contrato jsonb,
    _hash_linha text,
    _data_extracao timestamptz,
    _pagina integer,
    CONSTRAINT pk_reservas_snapshot PRIMARY KEY (_id_snapshot)
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_reservas_snapshot_dia ON bronze.reservas_snapshot (_data_snapshot, idreserva);
CREATE INDEX IF NOT EXISTS ix_reservas_snapshot_data ON bronze.reservas_snapshot (_data_snapshot);

-- ===== reservas_contratos (reservas/contratos) =====
CREATE TABLE IF NOT EXISTS bronze.reservas_contratos (
    _id_tecnico bigint GENERATED ALWAYS AS IDENTITY,
    referencia numeric,
    referencia_data timestamptz,
    ativo text,
    idreservacontrato numeric,
    idreserva numeric,
    data_cad timestamptz,
    idcontrato numeric,
    idgrupo text,
    idtipo numeric,
    idusuariovalida text,
    idusuario_imobiliaria_valida text,
    idcorretor_valida text,
    idusuarioassina text,
    idusuario_imobiliaria_assina text,
    idcorretor_assina text,
    idusuariocancela text,
    idusuario_imobiliaria_cancela text,
    idcorretor_cancela text,
    assinado text,
    validado text,
    cancelado text,
    visualizacao numeric,
    idusuario numeric,
    idusuario_imobiliaria text,
    idcorretor text,
    data_entrega text,
    justificativa text,
    nao_assinado text,
    nao_validado text,
    arquivo text,
    arquivo_tipo text,
    arquivo_tamanho numeric,
    arquivo_servidor text,
    arquivo_servidor_word text,
    iniciado_geracao_word text,
    data_iniciado_geracao_word timestamptz,
    idusuario_correspondente text,
    idusuario_correspondente_valida text,
    idusuario_correspondente_assina text,
    idusuario_correspondente_cancela text,
    idlancamento text,
    idreserva_contrato_lancamento text,
    imagem_comprimida text,
    tipo_assinatura_digital text,
    post jsonb,
    data_sincronizacao timestamptz,
    _hash_linha text NOT NULL,
    _data_extracao timestamptz NOT NULL DEFAULT now(),
    _pagina integer,
    CONSTRAINT pk_reservas_contratos PRIMARY KEY (_id_tecnico)
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_reservas_contratos_chave ON bronze.reservas_contratos (idreservacontrato);
-- (índice por id de negócio garantido por ux_reservas_contratos_chave em idreservacontrato)
CREATE TABLE IF NOT EXISTS bronze.reservas_contratos_snapshot (
    _id_snapshot bigint GENERATED ALWAYS AS IDENTITY,
    _data_snapshot date NOT NULL DEFAULT CURRENT_DATE,
    referencia numeric,
    referencia_data timestamptz,
    ativo text,
    idreservacontrato numeric,
    idreserva numeric,
    data_cad timestamptz,
    idcontrato numeric,
    idgrupo text,
    idtipo numeric,
    idusuariovalida text,
    idusuario_imobiliaria_valida text,
    idcorretor_valida text,
    idusuarioassina text,
    idusuario_imobiliaria_assina text,
    idcorretor_assina text,
    idusuariocancela text,
    idusuario_imobiliaria_cancela text,
    idcorretor_cancela text,
    assinado text,
    validado text,
    cancelado text,
    visualizacao numeric,
    idusuario numeric,
    idusuario_imobiliaria text,
    idcorretor text,
    data_entrega text,
    justificativa text,
    nao_assinado text,
    nao_validado text,
    arquivo text,
    arquivo_tipo text,
    arquivo_tamanho numeric,
    arquivo_servidor text,
    arquivo_servidor_word text,
    iniciado_geracao_word text,
    data_iniciado_geracao_word timestamptz,
    idusuario_correspondente text,
    idusuario_correspondente_valida text,
    idusuario_correspondente_assina text,
    idusuario_correspondente_cancela text,
    idlancamento text,
    idreserva_contrato_lancamento text,
    imagem_comprimida text,
    tipo_assinatura_digital text,
    post jsonb,
    data_sincronizacao timestamptz,
    _hash_linha text,
    _data_extracao timestamptz,
    _pagina integer,
    CONSTRAINT pk_reservas_contratos_snapshot PRIMARY KEY (_id_snapshot)
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_reservas_contratos_snapshot_dia ON bronze.reservas_contratos_snapshot (_data_snapshot, idreservacontrato);
CREATE INDEX IF NOT EXISTS ix_reservas_contratos_snapshot_data ON bronze.reservas_contratos_snapshot (_data_snapshot);

-- ===== reservas_comissoes (reservas/comissoes) =====
CREATE TABLE IF NOT EXISTS bronze.reservas_comissoes (
    _id_tecnico bigint GENERATED ALWAYS AS IDENTITY,
    referencia numeric,
    referencia_data timestamptz,
    ativo text,
    id numeric,
    data_cad timestamptz,
    diferenca text,
    tipo text,
    valor numeric,
    porcentagem numeric,
    descricao text,
    idreserva numeric,
    idimobiliaria numeric,
    idcorretor numeric,
    comissao_tipo text,
    comissao_pagamento_tipo text,
    codigointerno text,
    tipo_valor text,
    forma_pagamento text,
    pago_pela_condicao_reserva text,
    contrato text,
    para text,
    quem numeric,
    ordem numeric,
    enviar_pagadoria text,
    editado text,
    para_pagamento text,
    idusuario_nivel text,
    idusuario_categoria text,
    idcorretor_nivel text,
    idcorretor_categoria text,
    fifty text,
    fifty_idreferencia text,
    id_sub_regra_comissao text,
    idreserva_comissao_lancamento text,
    valor_porcentagem_premiacao text,
    _hash_linha text NOT NULL,
    _data_extracao timestamptz NOT NULL DEFAULT now(),
    _pagina integer,
    CONSTRAINT pk_reservas_comissoes PRIMARY KEY (_id_tecnico)
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_reservas_comissoes_chave ON bronze.reservas_comissoes (id);
-- (índice por id de negócio garantido por ux_reservas_comissoes_chave em id)
CREATE TABLE IF NOT EXISTS bronze.reservas_comissoes_snapshot (
    _id_snapshot bigint GENERATED ALWAYS AS IDENTITY,
    _data_snapshot date NOT NULL DEFAULT CURRENT_DATE,
    referencia numeric,
    referencia_data timestamptz,
    ativo text,
    id numeric,
    data_cad timestamptz,
    diferenca text,
    tipo text,
    valor numeric,
    porcentagem numeric,
    descricao text,
    idreserva numeric,
    idimobiliaria numeric,
    idcorretor numeric,
    comissao_tipo text,
    comissao_pagamento_tipo text,
    codigointerno text,
    tipo_valor text,
    forma_pagamento text,
    pago_pela_condicao_reserva text,
    contrato text,
    para text,
    quem numeric,
    ordem numeric,
    enviar_pagadoria text,
    editado text,
    para_pagamento text,
    idusuario_nivel text,
    idusuario_categoria text,
    idcorretor_nivel text,
    idcorretor_categoria text,
    fifty text,
    fifty_idreferencia text,
    id_sub_regra_comissao text,
    idreserva_comissao_lancamento text,
    valor_porcentagem_premiacao text,
    _hash_linha text,
    _data_extracao timestamptz,
    _pagina integer,
    CONSTRAINT pk_reservas_comissoes_snapshot PRIMARY KEY (_id_snapshot)
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_reservas_comissoes_snapshot_dia ON bronze.reservas_comissoes_snapshot (_data_snapshot, id);
CREATE INDEX IF NOT EXISTS ix_reservas_comissoes_snapshot_data ON bronze.reservas_comissoes_snapshot (_data_snapshot);

-- ===== reservas_historico_situacoes (reservas/historico/situacoes) =====
CREATE TABLE IF NOT EXISTS bronze.reservas_historico_situacoes (
    _id_tecnico bigint GENERATED ALWAYS AS IDENTITY,
    referencia numeric,
    referencia_data timestamptz,
    ativo text,
    idhistorico numeric,
    idreserva numeric,
    data_cad timestamptz,
    de numeric,
    para numeric,
    de_nome text,
    para_nome text,
    usuario text,
    idusuario numeric,
    _hash_linha text NOT NULL,
    _data_extracao timestamptz NOT NULL DEFAULT now(),
    _pagina integer,
    CONSTRAINT pk_reservas_historico_situacoes PRIMARY KEY (_id_tecnico)
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_reservas_historico_situacoes_chave ON bronze.reservas_historico_situacoes (idhistorico);
-- (índice por id de negócio garantido por ux_reservas_historico_situacoes_chave em idhistorico)
CREATE TABLE IF NOT EXISTS bronze.reservas_historico_situacoes_snapshot (
    _id_snapshot bigint GENERATED ALWAYS AS IDENTITY,
    _data_snapshot date NOT NULL DEFAULT CURRENT_DATE,
    referencia numeric,
    referencia_data timestamptz,
    ativo text,
    idhistorico numeric,
    idreserva numeric,
    data_cad timestamptz,
    de numeric,
    para numeric,
    de_nome text,
    para_nome text,
    usuario text,
    idusuario numeric,
    _hash_linha text,
    _data_extracao timestamptz,
    _pagina integer,
    CONSTRAINT pk_reservas_historico_situacoes_snapshot PRIMARY KEY (_id_snapshot)
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_reservas_historico_situacoes_snapshot_dia ON bronze.reservas_historico_situacoes_snapshot (_data_snapshot, idhistorico);
CREATE INDEX IF NOT EXISTS ix_reservas_historico_situacoes_snapshot_data ON bronze.reservas_historico_situacoes_snapshot (_data_snapshot);

-- ===== reservas_condicoes (reservas/condicoes) =====
CREATE TABLE IF NOT EXISTS bronze.reservas_condicoes (
    _id_tecnico bigint GENERATED ALWAYS AS IDENTITY,
    referencia numeric,
    referencia_data timestamptz,
    ativo text,
    idreservascondicoes numeric,
    idreserva numeric,
    idserie numeric,
    serie text,
    parcela_quantidade numeric,
    valor numeric,
    valor_com_juros numeric,
    valor_com_comissao_fora_do_contrato numeric,
    valor_sem_comissao numeric,
    vencimento date,
    portador text,
    indexador text,
    data_reservas_condicoes timestamptz,
    data_modificacao timestamptz,
    _hash_linha text NOT NULL,
    _data_extracao timestamptz NOT NULL DEFAULT now(),
    _pagina integer,
    CONSTRAINT pk_reservas_condicoes PRIMARY KEY (_id_tecnico)
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_reservas_condicoes_chave ON bronze.reservas_condicoes (idreservascondicoes);
-- (índice por id de negócio garantido por ux_reservas_condicoes_chave em idreservascondicoes)
CREATE TABLE IF NOT EXISTS bronze.reservas_condicoes_snapshot (
    _id_snapshot bigint GENERATED ALWAYS AS IDENTITY,
    _data_snapshot date NOT NULL DEFAULT CURRENT_DATE,
    referencia numeric,
    referencia_data timestamptz,
    ativo text,
    idreservascondicoes numeric,
    idreserva numeric,
    idserie numeric,
    serie text,
    parcela_quantidade numeric,
    valor numeric,
    valor_com_juros numeric,
    valor_com_comissao_fora_do_contrato numeric,
    valor_sem_comissao numeric,
    vencimento date,
    portador text,
    indexador text,
    data_reservas_condicoes timestamptz,
    data_modificacao timestamptz,
    _hash_linha text,
    _data_extracao timestamptz,
    _pagina integer,
    CONSTRAINT pk_reservas_condicoes_snapshot PRIMARY KEY (_id_snapshot)
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_reservas_condicoes_snapshot_dia ON bronze.reservas_condicoes_snapshot (_data_snapshot, idreservascondicoes);
CREATE INDEX IF NOT EXISTS ix_reservas_condicoes_snapshot_data ON bronze.reservas_condicoes_snapshot (_data_snapshot);

-- ===== leads (leads) =====
CREATE TABLE IF NOT EXISTS bronze.leads (
    _id_tecnico bigint GENERATED ALWAYS AS IDENTITY,
    referencia numeric,
    referencia_data timestamptz,
    ativo text,
    idlead numeric,
    idsituacao numeric,
    situacao text,
    data_cad timestamptz,
    nome text,
    email text,
    telefone text,
    documento_cliente numeric,
    cep_cliente text,
    idponto_venda numeric,
    ponto_venda text,
    conversao_original text,
    conversao_ultimo text,
    idempreendimento_primeiro numeric,
    empreendimento_primeiro text,
    idempreendimento_ultimo numeric,
    empreendimento_ultimo text,
    idmotivo numeric,
    motivo text,
    idgestor numeric,
    gestor text,
    idcorretor numeric,
    corretor text,
    data_associacao_corretor text,
    idimobiliaria numeric,
    imobiliaria text,
    feedback text,
    origem text,
    origem_ultimo text,
    midia_ultimo text,
    midia_original text,
    renda_familiar text,
    motivo_cancelamento text,
    data_cancelamento timestamptz,
    data_ultima_interacao timestamptz,
    ultima_data_conversao timestamptz,
    data_reativacao text,
    idsituacao_anterior numeric,
    nome_situacao_anterior_lead text,
    descricao_motivo_cancelamento text,
    submotivo_cancelamento text,
    possibilidade_venda numeric,
    inserido_bolsao text,
    data_primeira_interacao_gestor timestamptz,
    data_primeira_interacao_corretor timestamptz,
    score numeric,
    idgestor_ultimo numeric,
    gestor_ultimo text,
    idcorretor_ultimo numeric,
    corretor_ultimo text,
    idcorretor_penultimo numeric,
    idimobiliaria_ultimo numeric,
    corretor_penultimo text,
    nome_momento_lead text,
    novo text,
    retorno text,
    data_ultima_alteracao timestamptz,
    estado text,
    cidade text,
    regiao text,
    vencido text,
    data_vencimento timestamptz,
    profissao text,
    tags text,
    conversao text,
    idempreendimento numeric,
    codigointerno_empreendimento numeric,
    empreendimento text,
    caracteristicas text,
    reserva numeric,
    origem_nome text,
    origem_ultimo_nome text,
    campos_adicionais jsonb,
    _hash_linha text NOT NULL,
    _data_extracao timestamptz NOT NULL DEFAULT now(),
    _pagina integer,
    CONSTRAINT pk_leads PRIMARY KEY (_id_tecnico)
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_leads_chave ON bronze.leads (idlead);
-- (índice por id de negócio garantido por ux_leads_chave em idlead)
CREATE TABLE IF NOT EXISTS bronze.leads_snapshot (
    _id_snapshot bigint GENERATED ALWAYS AS IDENTITY,
    _data_snapshot date NOT NULL DEFAULT CURRENT_DATE,
    referencia numeric,
    referencia_data timestamptz,
    ativo text,
    idlead numeric,
    idsituacao numeric,
    situacao text,
    data_cad timestamptz,
    nome text,
    email text,
    telefone text,
    documento_cliente numeric,
    cep_cliente text,
    idponto_venda numeric,
    ponto_venda text,
    conversao_original text,
    conversao_ultimo text,
    idempreendimento_primeiro numeric,
    empreendimento_primeiro text,
    idempreendimento_ultimo numeric,
    empreendimento_ultimo text,
    idmotivo numeric,
    motivo text,
    idgestor numeric,
    gestor text,
    idcorretor numeric,
    corretor text,
    data_associacao_corretor text,
    idimobiliaria numeric,
    imobiliaria text,
    feedback text,
    origem text,
    origem_ultimo text,
    midia_ultimo text,
    midia_original text,
    renda_familiar text,
    motivo_cancelamento text,
    data_cancelamento timestamptz,
    data_ultima_interacao timestamptz,
    ultima_data_conversao timestamptz,
    data_reativacao text,
    idsituacao_anterior numeric,
    nome_situacao_anterior_lead text,
    descricao_motivo_cancelamento text,
    submotivo_cancelamento text,
    possibilidade_venda numeric,
    inserido_bolsao text,
    data_primeira_interacao_gestor timestamptz,
    data_primeira_interacao_corretor timestamptz,
    score numeric,
    idgestor_ultimo numeric,
    gestor_ultimo text,
    idcorretor_ultimo numeric,
    corretor_ultimo text,
    idcorretor_penultimo numeric,
    idimobiliaria_ultimo numeric,
    corretor_penultimo text,
    nome_momento_lead text,
    novo text,
    retorno text,
    data_ultima_alteracao timestamptz,
    estado text,
    cidade text,
    regiao text,
    vencido text,
    data_vencimento timestamptz,
    profissao text,
    tags text,
    conversao text,
    idempreendimento numeric,
    codigointerno_empreendimento numeric,
    empreendimento text,
    caracteristicas text,
    reserva numeric,
    origem_nome text,
    origem_ultimo_nome text,
    campos_adicionais jsonb,
    _hash_linha text,
    _data_extracao timestamptz,
    _pagina integer,
    CONSTRAINT pk_leads_snapshot PRIMARY KEY (_id_snapshot)
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_leads_snapshot_dia ON bronze.leads_snapshot (_data_snapshot, idlead);
CREATE INDEX IF NOT EXISTS ix_leads_snapshot_data ON bronze.leads_snapshot (_data_snapshot);

-- ===== leads_infos (leads/infos) =====
CREATE TABLE IF NOT EXISTS bronze.leads_infos (
    _id_tecnico bigint GENERATED ALWAYS AS IDENTITY,
    referencia numeric,
    referencia_data timestamptz,
    ativo text,
    idlead numeric,
    tags text,
    conversoes text,
    origens text,
    data_ultima_alteracao timestamptz,
    responsavel text,
    _hash_linha text NOT NULL,
    _data_extracao timestamptz NOT NULL DEFAULT now(),
    _pagina integer,
    CONSTRAINT pk_leads_infos PRIMARY KEY (_id_tecnico)
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_leads_infos_chave ON bronze.leads_infos (idlead);
-- (índice por id de negócio garantido por ux_leads_infos_chave em idlead)
CREATE TABLE IF NOT EXISTS bronze.leads_infos_snapshot (
    _id_snapshot bigint GENERATED ALWAYS AS IDENTITY,
    _data_snapshot date NOT NULL DEFAULT CURRENT_DATE,
    referencia numeric,
    referencia_data timestamptz,
    ativo text,
    idlead numeric,
    tags text,
    conversoes text,
    origens text,
    data_ultima_alteracao timestamptz,
    responsavel text,
    _hash_linha text,
    _data_extracao timestamptz,
    _pagina integer,
    CONSTRAINT pk_leads_infos_snapshot PRIMARY KEY (_id_snapshot)
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_leads_infos_snapshot_dia ON bronze.leads_infos_snapshot (_data_snapshot, idlead);
CREATE INDEX IF NOT EXISTS ix_leads_infos_snapshot_data ON bronze.leads_infos_snapshot (_data_snapshot);

-- ===== leads_conversoes (leads/conversoes) =====
CREATE TABLE IF NOT EXISTS bronze.leads_conversoes (
    _id_tecnico bigint GENERATED ALWAYS AS IDENTITY,
    referencia numeric,
    referencia_data timestamptz,
    ativo text,
    idlead_conversao numeric,
    idlead numeric,
    nome text,
    email text,
    telefone text,
    origem text,
    origem_conversao text,
    conversao date,
    data_cad timestamptz,
    midia text,
    midia_conversao text,
    gestor numeric,
    gestor_ultimo numeric,
    empreendimento_ultimo numeric,
    corretor numeric,
    corretor_ultimo text,
    imobiliaria numeric,
    imobiliaria_ultima numeric,
    empreendimentos_conversao jsonb,
    _hash_linha text NOT NULL,
    _data_extracao timestamptz NOT NULL DEFAULT now(),
    _pagina integer,
    CONSTRAINT pk_leads_conversoes PRIMARY KEY (_id_tecnico)
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_leads_conversoes_chave ON bronze.leads_conversoes (idlead_conversao);
-- (índice por id de negócio garantido por ux_leads_conversoes_chave em idlead_conversao)
CREATE TABLE IF NOT EXISTS bronze.leads_conversoes_snapshot (
    _id_snapshot bigint GENERATED ALWAYS AS IDENTITY,
    _data_snapshot date NOT NULL DEFAULT CURRENT_DATE,
    referencia numeric,
    referencia_data timestamptz,
    ativo text,
    idlead_conversao numeric,
    idlead numeric,
    nome text,
    email text,
    telefone text,
    origem text,
    origem_conversao text,
    conversao date,
    data_cad timestamptz,
    midia text,
    midia_conversao text,
    gestor numeric,
    gestor_ultimo numeric,
    empreendimento_ultimo numeric,
    corretor numeric,
    corretor_ultimo text,
    imobiliaria numeric,
    imobiliaria_ultima numeric,
    empreendimentos_conversao jsonb,
    _hash_linha text,
    _data_extracao timestamptz,
    _pagina integer,
    CONSTRAINT pk_leads_conversoes_snapshot PRIMARY KEY (_id_snapshot)
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_leads_conversoes_snapshot_dia ON bronze.leads_conversoes_snapshot (_data_snapshot, idlead_conversao);
CREATE INDEX IF NOT EXISTS ix_leads_conversoes_snapshot_data ON bronze.leads_conversoes_snapshot (_data_snapshot);

-- ===== comissoes (comissoes) =====
CREATE TABLE IF NOT EXISTS bronze.comissoes (
    _id_tecnico bigint GENERATED ALWAYS AS IDENTITY,
    referencia numeric,
    referencia_data timestamptz,
    ativo text,
    idcomissao numeric,
    situacao text,
    idsituacao numeric,
    idreserva numeric,
    corretor text,
    imobiliaria text,
    empreendimento text,
    etapa text,
    bloco text,
    unidade text,
    regiao text,
    cliente text,
    cep_cliente text,
    valor_contrato numeric,
    porcentagem_comissao numeric,
    valor_comissao numeric,
    valor_comissao_apagar numeric,
    valor_pagamento numeric,
    nota_fiscal text,
    data_pagamento text,
    data_cad timestamptz,
    _hash_linha text NOT NULL,
    _data_extracao timestamptz NOT NULL DEFAULT now(),
    _pagina integer,
    CONSTRAINT pk_comissoes PRIMARY KEY (_id_tecnico)
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_comissoes_chave ON bronze.comissoes (idcomissao);
-- (índice por id de negócio garantido por ux_comissoes_chave em idcomissao)
CREATE TABLE IF NOT EXISTS bronze.comissoes_snapshot (
    _id_snapshot bigint GENERATED ALWAYS AS IDENTITY,
    _data_snapshot date NOT NULL DEFAULT CURRENT_DATE,
    referencia numeric,
    referencia_data timestamptz,
    ativo text,
    idcomissao numeric,
    situacao text,
    idsituacao numeric,
    idreserva numeric,
    corretor text,
    imobiliaria text,
    empreendimento text,
    etapa text,
    bloco text,
    unidade text,
    regiao text,
    cliente text,
    cep_cliente text,
    valor_contrato numeric,
    porcentagem_comissao numeric,
    valor_comissao numeric,
    valor_comissao_apagar numeric,
    valor_pagamento numeric,
    nota_fiscal text,
    data_pagamento text,
    data_cad timestamptz,
    _hash_linha text,
    _data_extracao timestamptz,
    _pagina integer,
    CONSTRAINT pk_comissoes_snapshot PRIMARY KEY (_id_snapshot)
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_comissoes_snapshot_dia ON bronze.comissoes_snapshot (_data_snapshot, idcomissao);
CREATE INDEX IF NOT EXISTS ix_comissoes_snapshot_data ON bronze.comissoes_snapshot (_data_snapshot);

-- ===== comissoes_pagamentos (comissoes/pagamentos) =====
CREATE TABLE IF NOT EXISTS bronze.comissoes_pagamentos (
    _id_tecnico bigint GENERATED ALWAYS AS IDENTITY,
    referencia numeric,
    referencia_data timestamptz,
    idcomissao numeric,
    idpagamento numeric,
    valor numeric,
    vencimento date,
    bloco text,
    unidade numeric,
    situacao text,
    idboleto text,
    _hash_linha text NOT NULL,
    _data_extracao timestamptz NOT NULL DEFAULT now(),
    _pagina integer,
    CONSTRAINT pk_comissoes_pagamentos PRIMARY KEY (_id_tecnico)
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_comissoes_pagamentos_chave ON bronze.comissoes_pagamentos (idpagamento);
-- (índice por id de negócio garantido por ux_comissoes_pagamentos_chave em idpagamento)
CREATE TABLE IF NOT EXISTS bronze.comissoes_pagamentos_snapshot (
    _id_snapshot bigint GENERATED ALWAYS AS IDENTITY,
    _data_snapshot date NOT NULL DEFAULT CURRENT_DATE,
    referencia numeric,
    referencia_data timestamptz,
    idcomissao numeric,
    idpagamento numeric,
    valor numeric,
    vencimento date,
    bloco text,
    unidade numeric,
    situacao text,
    idboleto text,
    _hash_linha text,
    _data_extracao timestamptz,
    _pagina integer,
    CONSTRAINT pk_comissoes_pagamentos_snapshot PRIMARY KEY (_id_snapshot)
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_comissoes_pagamentos_snapshot_dia ON bronze.comissoes_pagamentos_snapshot (_data_snapshot, idpagamento);
CREATE INDEX IF NOT EXISTS ix_comissoes_pagamentos_snapshot_data ON bronze.comissoes_pagamentos_snapshot (_data_snapshot);

-- ===== precadastros (precadastros) =====
CREATE TABLE IF NOT EXISTS bronze.precadastros (
    _id_tecnico bigint GENERATED ALWAYS AS IDENTITY,
    referencia numeric,
    referencia_data timestamptz,
    ativo text,
    idprecadastro numeric,
    codigointerno text,
    idsituacao numeric,
    situacao text,
    condicao_aprovada text,
    idempreendimento numeric,
    empreendimento text,
    idunidade text,
    unidade text,
    idcorretor numeric,
    corretor text,
    idimobiliaria numeric,
    imobiliaria text,
    idempresa numeric,
    empresa text,
    pessoa text,
    cep_cliente numeric,
    renda_cliente_principal numeric,
    idusuario_correspondente numeric,
    usuario_correspondente text,
    idpessoa numeric,
    idlead numeric,
    valor_avaliacao numeric,
    valor_aprovado numeric,
    valor_subsidio numeric,
    valor_total numeric,
    valor_fgts numeric,
    saldo_devedor numeric,
    prazo text,
    observacoes text,
    tabela text,
    valor_prestacao numeric,
    carta_credito text,
    vencimento_aprovacao date,
    idmotivo_reprovacao numeric,
    motivo_reprovacao text,
    descricao_motivo_reprovacao text,
    idmotivo_cancelamento numeric,
    motivo_cancelamento text,
    descricao_motivo_cancelamento text,
    sla_vencimento text,
    data_cad timestamptz,
    empresa_correspondente text,
    idsituacao_anterior numeric,
    situacao_anterior text,
    data_ultima_alteracao_situacao timestamptz,
    idintencao_compra numeric,
    intencao_compra text,
    renda_total numeric,
    campos_adicionais jsonb,
    _hash_linha text NOT NULL,
    _data_extracao timestamptz NOT NULL DEFAULT now(),
    _pagina integer,
    CONSTRAINT pk_precadastros PRIMARY KEY (_id_tecnico)
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_precadastros_chave ON bronze.precadastros (idprecadastro);
-- (índice por id de negócio garantido por ux_precadastros_chave em idprecadastro)
CREATE TABLE IF NOT EXISTS bronze.precadastros_snapshot (
    _id_snapshot bigint GENERATED ALWAYS AS IDENTITY,
    _data_snapshot date NOT NULL DEFAULT CURRENT_DATE,
    referencia numeric,
    referencia_data timestamptz,
    ativo text,
    idprecadastro numeric,
    codigointerno text,
    idsituacao numeric,
    situacao text,
    condicao_aprovada text,
    idempreendimento numeric,
    empreendimento text,
    idunidade text,
    unidade text,
    idcorretor numeric,
    corretor text,
    idimobiliaria numeric,
    imobiliaria text,
    idempresa numeric,
    empresa text,
    pessoa text,
    cep_cliente numeric,
    renda_cliente_principal numeric,
    idusuario_correspondente numeric,
    usuario_correspondente text,
    idpessoa numeric,
    idlead numeric,
    valor_avaliacao numeric,
    valor_aprovado numeric,
    valor_subsidio numeric,
    valor_total numeric,
    valor_fgts numeric,
    saldo_devedor numeric,
    prazo text,
    observacoes text,
    tabela text,
    valor_prestacao numeric,
    carta_credito text,
    vencimento_aprovacao date,
    idmotivo_reprovacao numeric,
    motivo_reprovacao text,
    descricao_motivo_reprovacao text,
    idmotivo_cancelamento numeric,
    motivo_cancelamento text,
    descricao_motivo_cancelamento text,
    sla_vencimento text,
    data_cad timestamptz,
    empresa_correspondente text,
    idsituacao_anterior numeric,
    situacao_anterior text,
    data_ultima_alteracao_situacao timestamptz,
    idintencao_compra numeric,
    intencao_compra text,
    renda_total numeric,
    campos_adicionais jsonb,
    _hash_linha text,
    _data_extracao timestamptz,
    _pagina integer,
    CONSTRAINT pk_precadastros_snapshot PRIMARY KEY (_id_snapshot)
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_precadastros_snapshot_dia ON bronze.precadastros_snapshot (_data_snapshot, idprecadastro);
CREATE INDEX IF NOT EXISTS ix_precadastros_snapshot_data ON bronze.precadastros_snapshot (_data_snapshot);

-- ===== precadastro_historico_situacoes (precadastro/historico/situacoes) =====
CREATE TABLE IF NOT EXISTS bronze.precadastro_historico_situacoes (
    _id_tecnico bigint GENERATED ALWAYS AS IDENTITY,
    referencia numeric,
    referencia_data timestamptz,
    ativo text,
    idhistorico numeric,
    idprecadastro numeric,
    data_cad timestamptz,
    usuario_modificou text,
    painel text,
    de numeric,
    para numeric,
    de_nome text,
    para_nome text,
    _hash_linha text NOT NULL,
    _data_extracao timestamptz NOT NULL DEFAULT now(),
    _pagina integer,
    CONSTRAINT pk_precadastro_historico_situacoes PRIMARY KEY (_id_tecnico)
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_precadastro_historico_situacoes_chave ON bronze.precadastro_historico_situacoes (idhistorico);
-- (índice por id de negócio garantido por ux_precadastro_historico_situacoes_chave em idhistorico)
CREATE TABLE IF NOT EXISTS bronze.precadastro_historico_situacoes_snapshot (
    _id_snapshot bigint GENERATED ALWAYS AS IDENTITY,
    _data_snapshot date NOT NULL DEFAULT CURRENT_DATE,
    referencia numeric,
    referencia_data timestamptz,
    ativo text,
    idhistorico numeric,
    idprecadastro numeric,
    data_cad timestamptz,
    usuario_modificou text,
    painel text,
    de numeric,
    para numeric,
    de_nome text,
    para_nome text,
    _hash_linha text,
    _data_extracao timestamptz,
    _pagina integer,
    CONSTRAINT pk_precadastro_historico_situacoes_snapshot PRIMARY KEY (_id_snapshot)
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_precadastro_historico_situacoes_snapshot_dia ON bronze.precadastro_historico_situacoes_snapshot (_data_snapshot, idhistorico);
CREATE INDEX IF NOT EXISTS ix_precadastro_historico_situacoes_snapshot_data ON bronze.precadastro_historico_situacoes_snapshot (_data_snapshot);

-- ===== vendas (vendas) =====
CREATE TABLE IF NOT EXISTS bronze.vendas (
    _id_tecnico bigint GENERATED ALWAYS AS IDENTITY,
    referencia numeric,
    referencia_data timestamptz,
    ativo text,
    idreserva numeric,
    data_reserva timestamptz,
    data_venda timestamptz,
    idhistorico numeric,
    data_historico timestamptz,
    aprovada text,
    valor_contrato numeric,
    contrato_interno text,
    idpessoa_cv numeric,
    idpessoa_int text,
    cliente text,
    idcliente numeric,
    documento_cliente text,
    email text,
    cidade text,
    cep_cliente text,
    renda numeric,
    sexo text,
    idade numeric,
    estado_civil text,
    idcorretor numeric,
    corretor text,
    idimobiliaria numeric,
    imobiliaria text,
    idempreendimento numeric,
    empreendimento text,
    codigointerno_empreendimento numeric,
    regiao text,
    planta text,
    etapa text,
    bloco text,
    idunidade numeric,
    unidade text,
    area_privativa numeric,
    campanha text,
    idmidia numeric,
    midia text,
    idtabela text,
    nometabela text,
    codigointernotabela text,
    idtipovenda numeric,
    tipovenda text,
    idlead numeric,
    associados jsonb,
    _hash_linha text NOT NULL,
    _data_extracao timestamptz NOT NULL DEFAULT now(),
    _pagina integer,
    CONSTRAINT pk_vendas PRIMARY KEY (_id_tecnico)
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_vendas_chave ON bronze.vendas (idreserva);
-- (índice por id de negócio garantido por ux_vendas_chave em idreserva)
CREATE TABLE IF NOT EXISTS bronze.vendas_snapshot (
    _id_snapshot bigint GENERATED ALWAYS AS IDENTITY,
    _data_snapshot date NOT NULL DEFAULT CURRENT_DATE,
    referencia numeric,
    referencia_data timestamptz,
    ativo text,
    idreserva numeric,
    data_reserva timestamptz,
    data_venda timestamptz,
    idhistorico numeric,
    data_historico timestamptz,
    aprovada text,
    valor_contrato numeric,
    contrato_interno text,
    idpessoa_cv numeric,
    idpessoa_int text,
    cliente text,
    idcliente numeric,
    documento_cliente text,
    email text,
    cidade text,
    cep_cliente text,
    renda numeric,
    sexo text,
    idade numeric,
    estado_civil text,
    idcorretor numeric,
    corretor text,
    idimobiliaria numeric,
    imobiliaria text,
    idempreendimento numeric,
    empreendimento text,
    codigointerno_empreendimento numeric,
    regiao text,
    planta text,
    etapa text,
    bloco text,
    idunidade numeric,
    unidade text,
    area_privativa numeric,
    campanha text,
    idmidia numeric,
    midia text,
    idtabela text,
    nometabela text,
    codigointernotabela text,
    idtipovenda numeric,
    tipovenda text,
    idlead numeric,
    associados jsonb,
    _hash_linha text,
    _data_extracao timestamptz,
    _pagina integer,
    CONSTRAINT pk_vendas_snapshot PRIMARY KEY (_id_snapshot)
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_vendas_snapshot_dia ON bronze.vendas_snapshot (_data_snapshot, idreserva);
CREATE INDEX IF NOT EXISTS ix_vendas_snapshot_data ON bronze.vendas_snapshot (_data_snapshot);

-- ===== distratos (distratos) =====
CREATE TABLE IF NOT EXISTS bronze.distratos (
    _id_tecnico bigint GENERATED ALWAYS AS IDENTITY,
    referencia numeric,
    referencia_data timestamptz,
    ativo text,
    idreserva numeric,
    aprovada text,
    data_cad timestamptz,
    situacao_data timestamptz,
    situacao_atual text,
    idsituacao numeric,
    idempreendimento numeric,
    codigointerno_empreendimento numeric,
    empreendimento text,
    regiao text,
    etapa text,
    bloco text,
    idunidade numeric,
    unidade numeric,
    venda text,
    idcliente numeric,
    cliente text,
    documento text,
    cep_cliente text,
    idcorretor numeric,
    corretor text,
    idimobiliaria numeric,
    imobiliaria text,
    motivo_distrato text,
    descricao_motivo_distrato text,
    valor_contrato numeric,
    data_sincronizacao timestamptz,
    _hash_linha text NOT NULL,
    _data_extracao timestamptz NOT NULL DEFAULT now(),
    _pagina integer,
    CONSTRAINT pk_distratos PRIMARY KEY (_id_tecnico)
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_distratos_chave ON bronze.distratos (idreserva);
-- (índice por id de negócio garantido por ux_distratos_chave em idreserva)
CREATE TABLE IF NOT EXISTS bronze.distratos_snapshot (
    _id_snapshot bigint GENERATED ALWAYS AS IDENTITY,
    _data_snapshot date NOT NULL DEFAULT CURRENT_DATE,
    referencia numeric,
    referencia_data timestamptz,
    ativo text,
    idreserva numeric,
    aprovada text,
    data_cad timestamptz,
    situacao_data timestamptz,
    situacao_atual text,
    idsituacao numeric,
    idempreendimento numeric,
    codigointerno_empreendimento numeric,
    empreendimento text,
    regiao text,
    etapa text,
    bloco text,
    idunidade numeric,
    unidade numeric,
    venda text,
    idcliente numeric,
    cliente text,
    documento text,
    cep_cliente text,
    idcorretor numeric,
    corretor text,
    idimobiliaria numeric,
    imobiliaria text,
    motivo_distrato text,
    descricao_motivo_distrato text,
    valor_contrato numeric,
    data_sincronizacao timestamptz,
    _hash_linha text,
    _data_extracao timestamptz,
    _pagina integer,
    CONSTRAINT pk_distratos_snapshot PRIMARY KEY (_id_snapshot)
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_distratos_snapshot_dia ON bronze.distratos_snapshot (_data_snapshot, idreserva);
CREATE INDEX IF NOT EXISTS ix_distratos_snapshot_data ON bronze.distratos_snapshot (_data_snapshot);

-- ===== unidades (unidades) =====
CREATE TABLE IF NOT EXISTS bronze.unidades (
    _id_tecnico bigint GENERATED ALWAYS AS IDENTITY,
    referencia numeric,
    referencia_data timestamptz,
    idempreendimento numeric,
    idempreendimento_int numeric,
    nome_empreendimento text,
    idtipo_empreendimento numeric,
    tipo_empreendimento text,
    idetapa numeric,
    idetapa_int numeric,
    etapa text,
    idbloco numeric,
    idbloco_int numeric,
    bloco text,
    area_privativa numeric,
    idunidade numeric,
    nome text,
    idunidade_int numeric,
    cib text,
    vagas_garagem numeric,
    andar text,
    area_comum numeric,
    coluna text,
    posicao text,
    tipologia text,
    tipo text,
    idtipo_int text,
    empresa_terceirizacao text,
    valor numeric,
    valor_avaliacao text,
    data_bloqueio date,
    data_entrega text,
    data_entrega_chaves text,
    agendar_a_partir date,
    liberar_a_partir date,
    plantas jsonb,
    campos_adicionais jsonb,
    situacao_reservada text,
    situacao_reservada_vencimento text,
    situacao_reservada_idsituacao text,
    situacao_reservada_nomesituacao text,
    situacao_cor_bg text,
    situacao_cor_nome text,
    situacao_nome text,
    situacao_reservada_inicio text,
    situacao_vendida numeric,
    situacao_vendida_idsituacao numeric,
    situacao_idmotivo numeric,
    situacao_bloqueados_internos text,
    situacao_bloqueada text,
    situacao_bloqueada_idmotivo numeric,
    situacao_bloqueada_motivo text,
    situacao_tipo_id text,
    situacao_tipo_nome text,
    situacao_para_venda numeric,
    situacao_mapa_disponibilidade numeric,
    situacao_possui_reserva_solicitacao_distrato text,
    _hash_linha text NOT NULL,
    _data_extracao timestamptz NOT NULL DEFAULT now(),
    _pagina integer,
    CONSTRAINT pk_unidades PRIMARY KEY (_id_tecnico)
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_unidades_chave ON bronze.unidades (idunidade);
-- (índice por id de negócio garantido por ux_unidades_chave em idunidade)
CREATE TABLE IF NOT EXISTS bronze.unidades_snapshot (
    _id_snapshot bigint GENERATED ALWAYS AS IDENTITY,
    _data_snapshot date NOT NULL DEFAULT CURRENT_DATE,
    referencia numeric,
    referencia_data timestamptz,
    idempreendimento numeric,
    idempreendimento_int numeric,
    nome_empreendimento text,
    idtipo_empreendimento numeric,
    tipo_empreendimento text,
    idetapa numeric,
    idetapa_int numeric,
    etapa text,
    idbloco numeric,
    idbloco_int numeric,
    bloco text,
    area_privativa numeric,
    idunidade numeric,
    nome text,
    idunidade_int numeric,
    cib text,
    vagas_garagem numeric,
    andar text,
    area_comum numeric,
    coluna text,
    posicao text,
    tipologia text,
    tipo text,
    idtipo_int text,
    empresa_terceirizacao text,
    valor numeric,
    valor_avaliacao text,
    data_bloqueio date,
    data_entrega text,
    data_entrega_chaves text,
    agendar_a_partir date,
    liberar_a_partir date,
    plantas jsonb,
    campos_adicionais jsonb,
    situacao_reservada text,
    situacao_reservada_vencimento text,
    situacao_reservada_idsituacao text,
    situacao_reservada_nomesituacao text,
    situacao_cor_bg text,
    situacao_cor_nome text,
    situacao_nome text,
    situacao_reservada_inicio text,
    situacao_vendida numeric,
    situacao_vendida_idsituacao numeric,
    situacao_idmotivo numeric,
    situacao_bloqueados_internos text,
    situacao_bloqueada text,
    situacao_bloqueada_idmotivo numeric,
    situacao_bloqueada_motivo text,
    situacao_tipo_id text,
    situacao_tipo_nome text,
    situacao_para_venda numeric,
    situacao_mapa_disponibilidade numeric,
    situacao_possui_reserva_solicitacao_distrato text,
    _hash_linha text,
    _data_extracao timestamptz,
    _pagina integer,
    CONSTRAINT pk_unidades_snapshot PRIMARY KEY (_id_snapshot)
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_unidades_snapshot_dia ON bronze.unidades_snapshot (_data_snapshot, idunidade);
CREATE INDEX IF NOT EXISTS ix_unidades_snapshot_data ON bronze.unidades_snapshot (_data_snapshot);

-- ===== corretores (corretores) =====
CREATE TABLE IF NOT EXISTS bronze.corretores (
    _id_tecnico bigint GENERATED ALWAYS AS IDENTITY,
    referencia numeric,
    referencia_data timestamptz,
    ativo text,
    ativo_login text,
    idcorretor numeric,
    idimobiliaria numeric,
    data_cad timestamptz,
    documento text,
    nome text,
    apelido text,
    avatar text,
    avatar_nome text,
    avatar_servidor text,
    avatar_tipo text,
    avatar_tamanho numeric,
    sexo text,
    estado_civil text,
    data_nasc date,
    telefone text,
    celular text,
    rg numeric,
    rg_orgao_expedidor text,
    data_emissao_rg text,
    data_readmissao text,
    numero_pis text,
    naturalidade text,
    pais text,
    possui_filhos text,
    dependentes text,
    tamanho_camisa text,
    razao_social text,
    contrato_social_nire text,
    inscricao_estadual text,
    cep text,
    logradouro text,
    endereco text,
    bairro text,
    numero text,
    complemento text,
    estado text,
    cidade text,
    grau_instrucao text,
    curso text,
    ano_conclusao text,
    email text,
    imobiliaria text,
    categoria text,
    nivel text,
    participa_roleta_online text,
    classificacao text,
    codigointerno text,
    identificador text,
    profissional_experiencia_ramo_imobiliario text,
    profissional_quanto_tempo text,
    profissional_ultima_atual_empresa text,
    profissional_segmento text,
    profissional_data_inicio text,
    profissional_data_fim text,
    profissional_motivo_saida text,
    profissional_superior_imediato text,
    profissional_telefone text,
    profissional_cargo_inicial text,
    profissional_cargo_final text,
    profissional_descricao_atividades text,
    profissional_ultimos_atuais_ganhos text,
    profissional_expectativa_ganhos text,
    tipo_creci text,
    creci numeric,
    situacao_creci text,
    estado_creci text,
    cidade_creci text,
    vencimento_creci text,
    tipo_conta text,
    banco text,
    nome_agencia text,
    numero_agencia text,
    digito_agencia text,
    numero_conta text,
    digito_conta text,
    cpf_favorecido text,
    nome_favorecido text,
    cnpj text,
    inscricao_municipal text,
    ju_cep text,
    ju_logradouro text,
    ju_endereco text,
    ju_bairro text,
    ju_numero text,
    ju_complemento text,
    ju_estado text,
    ju_cidade text,
    cnpj_faturamento text,
    razaosocial_faturamento text,
    nomefantasia_faturamento text,
    representante_nome text,
    representante_telefone text,
    representante_celular text,
    representante_email text,
    representante_rg text,
    representante_documento text,
    representante_creci text,
    representante_vencimento_creci text,
    representante_data_nasc text,
    representante_quantidade_filhos text,
    banco_tipo_doc text,
    banco_cpf_titular text,
    banco_cnpj_titular text,
    data_ult_hist timestamptz,
    _hash_linha text NOT NULL,
    _data_extracao timestamptz NOT NULL DEFAULT now(),
    _pagina integer,
    CONSTRAINT pk_corretores PRIMARY KEY (_id_tecnico)
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_corretores_chave ON bronze.corretores (idcorretor);
-- (índice por id de negócio garantido por ux_corretores_chave em idcorretor)
CREATE TABLE IF NOT EXISTS bronze.corretores_snapshot (
    _id_snapshot bigint GENERATED ALWAYS AS IDENTITY,
    _data_snapshot date NOT NULL DEFAULT CURRENT_DATE,
    referencia numeric,
    referencia_data timestamptz,
    ativo text,
    ativo_login text,
    idcorretor numeric,
    idimobiliaria numeric,
    data_cad timestamptz,
    documento text,
    nome text,
    apelido text,
    avatar text,
    avatar_nome text,
    avatar_servidor text,
    avatar_tipo text,
    avatar_tamanho numeric,
    sexo text,
    estado_civil text,
    data_nasc date,
    telefone text,
    celular text,
    rg numeric,
    rg_orgao_expedidor text,
    data_emissao_rg text,
    data_readmissao text,
    numero_pis text,
    naturalidade text,
    pais text,
    possui_filhos text,
    dependentes text,
    tamanho_camisa text,
    razao_social text,
    contrato_social_nire text,
    inscricao_estadual text,
    cep text,
    logradouro text,
    endereco text,
    bairro text,
    numero text,
    complemento text,
    estado text,
    cidade text,
    grau_instrucao text,
    curso text,
    ano_conclusao text,
    email text,
    imobiliaria text,
    categoria text,
    nivel text,
    participa_roleta_online text,
    classificacao text,
    codigointerno text,
    identificador text,
    profissional_experiencia_ramo_imobiliario text,
    profissional_quanto_tempo text,
    profissional_ultima_atual_empresa text,
    profissional_segmento text,
    profissional_data_inicio text,
    profissional_data_fim text,
    profissional_motivo_saida text,
    profissional_superior_imediato text,
    profissional_telefone text,
    profissional_cargo_inicial text,
    profissional_cargo_final text,
    profissional_descricao_atividades text,
    profissional_ultimos_atuais_ganhos text,
    profissional_expectativa_ganhos text,
    tipo_creci text,
    creci numeric,
    situacao_creci text,
    estado_creci text,
    cidade_creci text,
    vencimento_creci text,
    tipo_conta text,
    banco text,
    nome_agencia text,
    numero_agencia text,
    digito_agencia text,
    numero_conta text,
    digito_conta text,
    cpf_favorecido text,
    nome_favorecido text,
    cnpj text,
    inscricao_municipal text,
    ju_cep text,
    ju_logradouro text,
    ju_endereco text,
    ju_bairro text,
    ju_numero text,
    ju_complemento text,
    ju_estado text,
    ju_cidade text,
    cnpj_faturamento text,
    razaosocial_faturamento text,
    nomefantasia_faturamento text,
    representante_nome text,
    representante_telefone text,
    representante_celular text,
    representante_email text,
    representante_rg text,
    representante_documento text,
    representante_creci text,
    representante_vencimento_creci text,
    representante_data_nasc text,
    representante_quantidade_filhos text,
    banco_tipo_doc text,
    banco_cpf_titular text,
    banco_cnpj_titular text,
    data_ult_hist timestamptz,
    _hash_linha text,
    _data_extracao timestamptz,
    _pagina integer,
    CONSTRAINT pk_corretores_snapshot PRIMARY KEY (_id_snapshot)
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_corretores_snapshot_dia ON bronze.corretores_snapshot (_data_snapshot, idcorretor);
CREATE INDEX IF NOT EXISTS ix_corretores_snapshot_data ON bronze.corretores_snapshot (_data_snapshot);

-- ===== imobiliarias (imobiliarias) =====
CREATE TABLE IF NOT EXISTS bronze.imobiliarias (
    _id_tecnico bigint GENERATED ALWAYS AS IDENTITY,
    referencia numeric,
    referencia_data timestamptz,
    idimobiliaria numeric,
    ativo text,
    ativo_painel text,
    data_cad timestamptz,
    idestado numeric,
    idcidade numeric,
    nome text,
    razao_social text,
    cnpj numeric,
    cnpj_faturamento text,
    idlogradouro numeric,
    endereco text,
    complemento text,
    numero text,
    bairro text,
    cep text,
    telefone text,
    celular text,
    email text,
    creci text,
    avatar_nome text,
    avatar_servidor text,
    avatar_tipo text,
    avatar_tamanho text,
    validade_creci date,
    gerente_nome text,
    gerente_cpf text,
    gerente_telefone text,
    gerente_celular text,
    gerente_email text,
    sigla text,
    codigointerno text,
    observacoes text,
    micro_empresa text,
    inscricao_estadual text,
    inscricao_municipal text,
    tipo_conta text,
    idbanco text,
    nome_agencia text,
    numero_agencia text,
    digito_agencia text,
    numero_conta text,
    digito_conta text,
    nome_favorecido text,
    cnpj_favorecido text,
    alterar_login_corretor text,
    escala_plantao text,
    idimobiliaria_nov text,
    bloqueado_recebimento_pagamento_comissao text,
    autocadastro_corretor text,
    diretor_nome text,
    diretor_cpf text,
    diretor_telefone text,
    diretor_celular text,
    diretor_email text,
    data_modificacao timestamptz,
    _hash_linha text NOT NULL,
    _data_extracao timestamptz NOT NULL DEFAULT now(),
    _pagina integer,
    CONSTRAINT pk_imobiliarias PRIMARY KEY (_id_tecnico)
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_imobiliarias_chave ON bronze.imobiliarias (idimobiliaria);
-- (índice por id de negócio garantido por ux_imobiliarias_chave em idimobiliaria)
CREATE TABLE IF NOT EXISTS bronze.imobiliarias_snapshot (
    _id_snapshot bigint GENERATED ALWAYS AS IDENTITY,
    _data_snapshot date NOT NULL DEFAULT CURRENT_DATE,
    referencia numeric,
    referencia_data timestamptz,
    idimobiliaria numeric,
    ativo text,
    ativo_painel text,
    data_cad timestamptz,
    idestado numeric,
    idcidade numeric,
    nome text,
    razao_social text,
    cnpj numeric,
    cnpj_faturamento text,
    idlogradouro numeric,
    endereco text,
    complemento text,
    numero text,
    bairro text,
    cep text,
    telefone text,
    celular text,
    email text,
    creci text,
    avatar_nome text,
    avatar_servidor text,
    avatar_tipo text,
    avatar_tamanho text,
    validade_creci date,
    gerente_nome text,
    gerente_cpf text,
    gerente_telefone text,
    gerente_celular text,
    gerente_email text,
    sigla text,
    codigointerno text,
    observacoes text,
    micro_empresa text,
    inscricao_estadual text,
    inscricao_municipal text,
    tipo_conta text,
    idbanco text,
    nome_agencia text,
    numero_agencia text,
    digito_agencia text,
    numero_conta text,
    digito_conta text,
    nome_favorecido text,
    cnpj_favorecido text,
    alterar_login_corretor text,
    escala_plantao text,
    idimobiliaria_nov text,
    bloqueado_recebimento_pagamento_comissao text,
    autocadastro_corretor text,
    diretor_nome text,
    diretor_cpf text,
    diretor_telefone text,
    diretor_celular text,
    diretor_email text,
    data_modificacao timestamptz,
    _hash_linha text,
    _data_extracao timestamptz,
    _pagina integer,
    CONSTRAINT pk_imobiliarias_snapshot PRIMARY KEY (_id_snapshot)
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_imobiliarias_snapshot_dia ON bronze.imobiliarias_snapshot (_data_snapshot, idimobiliaria);
CREATE INDEX IF NOT EXISTS ix_imobiliarias_snapshot_data ON bronze.imobiliarias_snapshot (_data_snapshot);

-- ===== pessoas (pessoas) =====
CREATE TABLE IF NOT EXISTS bronze.pessoas (
    _id_tecnico bigint GENERATED ALWAYS AS IDENTITY,
    referencia numeric,
    referencia_data timestamptz,
    ativo text,
    idpessoa numeric,
    idpessoa_int text,
    idpessoa_legado text,
    data_cad timestamptz,
    ativo_painel text,
    ativo_login text,
    situacao text,
    validado text,
    documento_tipo text,
    documento numeric,
    pessoa_estrangeira text,
    nome text,
    reconhecimento_firma text,
    sexo text,
    data_nasc date,
    estado_civil text,
    data_casamento text,
    pacto_antenupcial_livro text,
    folha text,
    cartorio text,
    pais text,
    naturalidade text,
    possui_dependentes text,
    quantidade_dependentes text,
    possui_procuracao text,
    possui_pacto_antenupcial text,
    menor_nao_emancipado text,
    grau_instrucao text,
    renda_familiar text,
    marketing_pos_venda text,
    rg numeric,
    rg_orgao_emissor text,
    rg_data_emissao date,
    rne text,
    rne_orgao_emissor text,
    rne_data_emissao text,
    passaporte text,
    passaporte_orgao_emissor text,
    passaporte_data_emissao text,
    cnh text,
    cnh_orgao_emissor text,
    data_primeira_habilitacao_cnh text,
    data_fim_validade_cnh text,
    cnh_data_emissao text,
    rnm text,
    rnm_orgao_emissor text,
    rnm_data_emissao text,
    filiacao_mae text,
    filiacao_pai text,
    razao_social text,
    segmento_razao text,
    razao_social_anterior text,
    sucessao text,
    forma_constituicao text,
    data_constituicao text,
    numero_junta_comercial text,
    classificacao text,
    insc_estadual text,
    insc_municipal text,
    cep numeric,
    logradouro text,
    endereco text,
    bairro text,
    numero numeric,
    complemento text,
    estado text,
    cidade text,
    endereco_pais text,
    tipo_residencia text,
    reside_com text,
    valor_aluguel text,
    tempo_residencia numeric,
    tipo_correspondencia text,
    politicamente_exposta text,
    ppe_cargo text,
    ppe_exercicio text,
    suspeito text,
    residente_municipio_fronteira text,
    relacionamento_ppe text,
    relacionamento_ppe_nome text,
    relacionamento_ppe_parentesco text,
    relacionamento_ppe_cargo text,
    relacionamento_ppe_exercicio text,
    relacionamento_ppe_identificacao text,
    relacionamento_ppe_orgao_emissor text,
    relacionamento_ppe_data_nasc text,
    relacionamento_ppe_cpf text,
    numero_pis numeric,
    observacoes text,
    _hash_linha text NOT NULL,
    _data_extracao timestamptz NOT NULL DEFAULT now(),
    _pagina integer,
    CONSTRAINT pk_pessoas PRIMARY KEY (_id_tecnico)
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_pessoas_chave ON bronze.pessoas (idpessoa);
-- (índice por id de negócio garantido por ux_pessoas_chave em idpessoa)
CREATE TABLE IF NOT EXISTS bronze.pessoas_snapshot (
    _id_snapshot bigint GENERATED ALWAYS AS IDENTITY,
    _data_snapshot date NOT NULL DEFAULT CURRENT_DATE,
    referencia numeric,
    referencia_data timestamptz,
    ativo text,
    idpessoa numeric,
    idpessoa_int text,
    idpessoa_legado text,
    data_cad timestamptz,
    ativo_painel text,
    ativo_login text,
    situacao text,
    validado text,
    documento_tipo text,
    documento numeric,
    pessoa_estrangeira text,
    nome text,
    reconhecimento_firma text,
    sexo text,
    data_nasc date,
    estado_civil text,
    data_casamento text,
    pacto_antenupcial_livro text,
    folha text,
    cartorio text,
    pais text,
    naturalidade text,
    possui_dependentes text,
    quantidade_dependentes text,
    possui_procuracao text,
    possui_pacto_antenupcial text,
    menor_nao_emancipado text,
    grau_instrucao text,
    renda_familiar text,
    marketing_pos_venda text,
    rg numeric,
    rg_orgao_emissor text,
    rg_data_emissao date,
    rne text,
    rne_orgao_emissor text,
    rne_data_emissao text,
    passaporte text,
    passaporte_orgao_emissor text,
    passaporte_data_emissao text,
    cnh text,
    cnh_orgao_emissor text,
    data_primeira_habilitacao_cnh text,
    data_fim_validade_cnh text,
    cnh_data_emissao text,
    rnm text,
    rnm_orgao_emissor text,
    rnm_data_emissao text,
    filiacao_mae text,
    filiacao_pai text,
    razao_social text,
    segmento_razao text,
    razao_social_anterior text,
    sucessao text,
    forma_constituicao text,
    data_constituicao text,
    numero_junta_comercial text,
    classificacao text,
    insc_estadual text,
    insc_municipal text,
    cep numeric,
    logradouro text,
    endereco text,
    bairro text,
    numero numeric,
    complemento text,
    estado text,
    cidade text,
    endereco_pais text,
    tipo_residencia text,
    reside_com text,
    valor_aluguel text,
    tempo_residencia numeric,
    tipo_correspondencia text,
    politicamente_exposta text,
    ppe_cargo text,
    ppe_exercicio text,
    suspeito text,
    residente_municipio_fronteira text,
    relacionamento_ppe text,
    relacionamento_ppe_nome text,
    relacionamento_ppe_parentesco text,
    relacionamento_ppe_cargo text,
    relacionamento_ppe_exercicio text,
    relacionamento_ppe_identificacao text,
    relacionamento_ppe_orgao_emissor text,
    relacionamento_ppe_data_nasc text,
    relacionamento_ppe_cpf text,
    numero_pis numeric,
    observacoes text,
    _hash_linha text,
    _data_extracao timestamptz,
    _pagina integer,
    CONSTRAINT pk_pessoas_snapshot PRIMARY KEY (_id_snapshot)
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_pessoas_snapshot_dia ON bronze.pessoas_snapshot (_data_snapshot, idpessoa);
CREATE INDEX IF NOT EXISTS ix_pessoas_snapshot_data ON bronze.pessoas_snapshot (_data_snapshot);

-- ===== pessoas_profissional (pessoas/profissional) =====
-- DDL escrito à mão (gerar_ddl_bronze.py/descoberta_schema.py, usados pros outros 19
-- objetos, não existem mais no repo): tipos decididos por amostra ao vivo (500
-- registros, 24/ago/2026) + mesma convenção já usada em bronze.pessoas (CEP/número/
-- documento como numeric mesmo sendo identificador; datas soltas como text quando
-- não vêm em formato ISO consistente). 1 linha por idpessoa (8.465 registros na
-- origem contra 8.464 em bronze.pessoas — praticamente 1:1, confirmado ao vivo).
CREATE TABLE IF NOT EXISTS bronze.pessoas_profissional (
    _id_tecnico bigint GENERATED ALWAYS AS IDENTITY,
    referencia numeric,
    referencia_data timestamptz,
    ativo text,
    idpessoa numeric,
    idpessoa_int text,
    profissao_select text,
    profissao text,
    trabalho_nome_empresa text,
    trabalho_cnpj numeric,
    trabalho_pais text,
    trabalho_site text,
    trabalho_cargo text,
    remuneracao_bruta numeric,
    remuneracao_liquida numeric,
    trabalho_participacao_proprietario numeric,
    trabalho_telefone text,
    trabalho_celular text,
    trabalho_fax text,
    trabalho_email text,
    trabalho_cep numeric,
    logradouro_trabalho text,
    trabalho_endereco text,
    trabalho_bairro text,
    trabalho_numero numeric,
    complemento_trabalho text,
    trabalho_estado text,
    trabalho_cidade text,
    trabalho_endereco_pais text,
    trabalho_anterior_nome_empresa text,
    trabalho_anterior_cnpj numeric,
    trabalho_anterior_data_admissao text,
    trabalho_anterior_data_desligamento text,
    possui_outras_rendas text,
    valor_mensal_bruto numeric,
    valor_mensal_liquido numeric,
    renda_proveniente_de text,
    renda_comprovada_atraves_de text,
    possui_aplicacao_financeira text,
    valor_total_aplicacao numeric,
    rendimento_mensal_aplicacao numeric,
    banco_aplicacao text,
    pretende_utilizar_fgts text,
    valor_fgts numeric,
    possui_imovel text,
    possui_onus_imovel text,
    cep_imovel_proprietario numeric,
    endereco_imovel_proprietario text,
    bairro_imovel_proprietario text,
    estado_imovel_proprietario text,
    cidade_imovel_proprietario text,
    endereco_pais_imovel_proprietario text,
    _hash_linha text NOT NULL,
    _data_extracao timestamptz NOT NULL DEFAULT now(),
    _pagina integer,
    CONSTRAINT pk_pessoas_profissional PRIMARY KEY (_id_tecnico)
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_pessoas_profissional_chave ON bronze.pessoas_profissional (idpessoa);
CREATE TABLE IF NOT EXISTS bronze.pessoas_profissional_snapshot (
    _id_snapshot bigint GENERATED ALWAYS AS IDENTITY,
    _data_snapshot date NOT NULL DEFAULT CURRENT_DATE,
    referencia numeric,
    referencia_data timestamptz,
    ativo text,
    idpessoa numeric,
    idpessoa_int text,
    profissao_select text,
    profissao text,
    trabalho_nome_empresa text,
    trabalho_cnpj numeric,
    trabalho_pais text,
    trabalho_site text,
    trabalho_cargo text,
    remuneracao_bruta numeric,
    remuneracao_liquida numeric,
    trabalho_participacao_proprietario numeric,
    trabalho_telefone text,
    trabalho_celular text,
    trabalho_fax text,
    trabalho_email text,
    trabalho_cep numeric,
    logradouro_trabalho text,
    trabalho_endereco text,
    trabalho_bairro text,
    trabalho_numero numeric,
    complemento_trabalho text,
    trabalho_estado text,
    trabalho_cidade text,
    trabalho_endereco_pais text,
    trabalho_anterior_nome_empresa text,
    trabalho_anterior_cnpj numeric,
    trabalho_anterior_data_admissao text,
    trabalho_anterior_data_desligamento text,
    possui_outras_rendas text,
    valor_mensal_bruto numeric,
    valor_mensal_liquido numeric,
    renda_proveniente_de text,
    renda_comprovada_atraves_de text,
    possui_aplicacao_financeira text,
    valor_total_aplicacao numeric,
    rendimento_mensal_aplicacao numeric,
    banco_aplicacao text,
    pretende_utilizar_fgts text,
    valor_fgts numeric,
    possui_imovel text,
    possui_onus_imovel text,
    cep_imovel_proprietario numeric,
    endereco_imovel_proprietario text,
    bairro_imovel_proprietario text,
    estado_imovel_proprietario text,
    cidade_imovel_proprietario text,
    endereco_pais_imovel_proprietario text,
    _hash_linha text,
    _data_extracao timestamptz,
    _pagina integer,
    CONSTRAINT pk_pessoas_profissional_snapshot PRIMARY KEY (_id_snapshot)
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_pessoas_profissional_snapshot_dia ON bronze.pessoas_profissional_snapshot (_data_snapshot, idpessoa);
CREATE INDEX IF NOT EXISTS ix_pessoas_profissional_snapshot_data ON bronze.pessoas_profissional_snapshot (_data_snapshot);

-- ===== campos_adicionais (campos_adicionais) =====
CREATE TABLE IF NOT EXISTS bronze.campos_adicionais (
    _id_tecnico bigint GENERATED ALWAYS AS IDENTITY,
    referencia numeric,
    referencia_data timestamptz,
    ativo text,
    idcampo numeric,
    campo_nome text,
    idfuncionalidade numeric,
    funcionalidade text,
    valor text,
    data_cad timestamptz,
    data_modificacao text,
    _hash_linha text NOT NULL,
    _data_extracao timestamptz NOT NULL DEFAULT now(),
    _pagina integer,
    CONSTRAINT pk_campos_adicionais PRIMARY KEY (_id_tecnico)
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_campos_adicionais_chave ON bronze.campos_adicionais (_hash_linha);
CREATE TABLE IF NOT EXISTS bronze.campos_adicionais_snapshot (
    _id_snapshot bigint GENERATED ALWAYS AS IDENTITY,
    _data_snapshot date NOT NULL DEFAULT CURRENT_DATE,
    referencia numeric,
    referencia_data timestamptz,
    ativo text,
    idcampo numeric,
    campo_nome text,
    idfuncionalidade numeric,
    funcionalidade text,
    valor text,
    data_cad timestamptz,
    data_modificacao text,
    _hash_linha text,
    _data_extracao timestamptz,
    _pagina integer,
    CONSTRAINT pk_campos_adicionais_snapshot PRIMARY KEY (_id_snapshot)
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_campos_adicionais_snapshot_dia ON bronze.campos_adicionais_snapshot (_data_snapshot, _hash_linha);
CREATE INDEX IF NOT EXISTS ix_campos_adicionais_snapshot_data ON bronze.campos_adicionais_snapshot (_data_snapshot);
